linters:
  disable-all: true
  enable:
    - copyloopvar
    - gci
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/yaling888/clash)
      - default

run:
  # default concurrency is a available CPU number
  concurrency: 4

  # Define the Go version limit.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.17
  # go: '1.22'

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
